{
  "formatVersion": "1.1",
  "component": {
    "group": "net.geidea",
    "module": "networklogging",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "networklogging-1.0.0.aar",
          "url": "networklogging-1.0.0.aar",
          "size": 44440,
          "sha512": "0ae469513220d06562bde82397e3f0b26efd28e7d3c1b212ff8d20a2ef541f017869add44da3252154a9e7415ff61900cca8be2262c43b5305acbe94826436f7",
          "sha256": "f101333939781ddf96d9cd36687c7084a70cc1bf6703269a8cb7f2181e2a4ad6",
          "sha1": "2f64edbe0295721d29ad37f7ea93d91ed29ef4ea",
          "md5": "ff0fba9c27042f9a4f9fcb170440dc4c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "networklogging-1.0.0.aar",
          "url": "networklogging-1.0.0.aar",
          "size": 44440,
          "sha512": "0ae469513220d06562bde82397e3f0b26efd28e7d3c1b212ff8d20a2ef541f017869add44da3252154a9e7415ff61900cca8be2262c43b5305acbe94826436f7",
          "sha256": "f101333939781ddf96d9cd36687c7084a70cc1bf6703269a8cb7f2181e2a4ad6",
          "sha1": "2f64edbe0295721d29ad37f7ea93d91ed29ef4ea",
          "md5": "ff0fba9c27042f9a4f9fcb170440dc4c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "networklogging-1.0.0-sources.jar",
          "url": "networklogging-1.0.0-sources.jar",
          "size": 16817,
          "sha512": "8aa04a6b2d535ead9dc41b82ef84475fa790da904460aa26973d5169f7901a2685294501b2a36c740f1e5ec75f1483f674551b9e004a1fcee6593c6b557c4241",
          "sha256": "b13aee7f003ef822840b0ebf8adbcdb4ea728ecfe496634f9609acffb589564b",
          "sha1": "629eaf53cf384e5318ba08745552ea36becbde85",
          "md5": "12628bd373cdd3c83ef7a72c2b0a4973"
        }
      ]
    }
  ]
}
